//Generated by Framework Code Generator4/22/2020 9:41:05 PM
using System;
using System.Collections.Generic;

namespace Doctrin.DataLayer.Dtos
{
	public class DeleteUnitInDto 	{
			public int Id {get;set;}



	}
}
