//Generated by Framework Code Generator4/22/2020 9:41:05 PM
using System;
using System.Collections.Generic;

namespace Doctrin.DataLayer.Dtos
{
	public class DeleteUnitOutDto 	{
			public Int32 Id {get;set;}
			public Int32? ParentId {get;set;}
			public String Name {get;set;}
			public string Message {get;set;}



	}
}
