//Generated by Framework Code Generator4/19/2020 10:37:39 PM
using System;
using System.Collections.Generic;

namespace Doctrin.DataLayer.Dtos
{
	public class InsertUnitInDto 	{
			public int ParentId {get;set;}

            public string Name { get; set; }


	}
}
