//Generated by Framework Code Generator4/19/2020 10:37:39 PM
using System;
using System.Collections.Generic;

namespace Doctrin.DataLayer.Dtos
{
	public class InsertUnitOutDto 	{
			public Int32 Id {get;set;}
			public Int32? ParentId {get;set;}
			public string Message {get;set;}



	}
}
