//Generated by Framework Code Generator4/18/2020 9:35:58 PM
using System;
using System.Collections.Generic;

namespace Doctrin.DataLayer.Dtos
{
	public class ReadOneUnitOutDto 	{
			public Int32 Id {get;set;}
            public string Name { get; set; }
			public string Message {get;set;}



	}
}
