//Generated by Framework Code Generator4/18/2020 9:35:58 PM
using System;
using System.Collections.Generic;

namespace Doctrin.DataLayer.Dtos
{
	public class ReadOneUnitInDto 	{
			public int Id {get;set;}



	}
}
