//Generated by Framework Code Generator4/22/2020 9:41:07 PM
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Doctrin.Api.Controllers.Validators;
using Doctrin.Api.Resources;
using Doctrin.Core.Entities;
using Doctrin.Core.Services;
using Doctrin.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace Doctrin.Web
{
	[Route("api/[controller]")]
	public class OrganisationsController  : ControllerBase
    {

        private readonly IUnitService _unitService;
        private readonly ISettingService _settingService;
        private readonly IMapper _mapper;

        public OrganisationsController(IUnitService unitService,ISettingService settingService, IMapper mapper)
        {
            _unitService = unitService;
            _settingService = settingService;
            _mapper = mapper;
        }


        [HttpGet("{id}", Name= "GetUnit")]
        public async Task<ActionResult<UnitResource>> Get(int id)
        {
            if (id==0)
            {
                return BadRequest();
            }
            var unit = await _unitService.GetAsync(id);

            if (unit==null)
            {
                return NotFound();
            }
            var unitResource = _mapper.Map<Unit,UnitResource>(unit);

            return Ok(unitResource);
        }

        [HttpPost()]
        public async Task<ActionResult<UnitResource>> Post([FromBody] SaveUnitResource saveUnitResource)
        {
            var validator = new SaveUnitResourceValidator();
            var validationResult = await validator.ValidateAsync(saveUnitResource);

            if (!validationResult.IsValid)
                return BadRequest(validationResult.Errors); 

            var unitToCreate = _mapper.Map<SaveUnitResource, Unit>(saveUnitResource);

            var newUnit = await _unitService.Add(unitToCreate);

            var unit = await _unitService.GetAsync(newUnit.Id);

            var unitResource = _mapper.Map<Unit, UnitResource>(unit);

            return CreatedAtRoute("GetUnit",new {id =unit.Id}, unitResource);
        }


        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return BadRequest();

            var unit = await _unitService.GetAsync(id);

            if (unit == null)
                return NotFound();

            await _unitService.Delete(unit);

            return NoContent();
        }

        //[HttpGet("{unitId}/settings/{globalId}", Name = "GetSetting")]
        //public async Task<ActionResult<SettingResource>> Get(int unitId, string globalId)
        //{
        //    if (unitId == 0 || globalId == "")
        //    {
        //        return BadRequest();
        //    }
        //    var setting = await _settingService.GetSettingByUnit(unitId, globalId);

        //    if (setting == null)
        //    {
        //        return NotFound();
        //    }
        //    var settingResource = _mapper.Map<Setting, SettingResource>(setting);

        //    return Ok(settingResource);
        //}


    }
}
