//Generated by Framework Code Generator5/7/2020 9:00:36 PM
using Doctrin.Api.Resources;
using FluentValidation;
namespace Doctrin.Api.Validators
{
	public  class SaveShittingResourceValidator : AbstractValidator<SaveShittingResource>	{


		public SaveShittingResourceValidator() 
		{
			RuleFor(a => a.GlobalId)
			.MaximumLength(100)
			.NotEmpty()
			;
			RuleFor(a => a.Value)
			.MaximumLength(200)
			.NotEmpty()
			;
		}
	}
}
