//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using Doctrin.Api.Resources;
using FluentValidation;
namespace Doctrin.Api.Validators
{
	public  class SaveCrappingResourceValidator : AbstractValidator<SaveCrappingResource>	{


		public SaveCrappingResourceValidator() 
		{
			RuleFor(a => a.Value)
			.MaximumLength(200)
			.NotEmpty()
			;
		}
	}
}
