//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;

namespace Doctrin.Core.Services
{
	public  interface ICrappingService 	{

		Task<Crapping> GetAsync(int id);
		Task DeleteAsync(Crapping crappingToDelete);
		Task<Crapping> AddAsync(Crapping crappingToCreate);
	}
}
