//Generated by Framework Code Generator5/5/2020 1:14:09 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;

namespace Doctrin.Core.Services
{
	public interface ISetting2Service 	{


		Task<Shitting> GetSettingByUnitAsync(int unitId, int id);
		Task AddSettingByUnitAsync(int unitId, Shitting shitting);
		Task DeleteAsync(Shitting shitting);
		Task<Shitting> AddAsync(int unitId, Shitting shitting);
	}
}
