//Generated by Framework Code Generator5/7/2020 9:00:36 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;

namespace Doctrin.Core.Services
{
	public  interface IShittingService 	{

		Task<Shitting> GetShittingByUnitAsync(int unitId, int id);
		Task<Shitting> AddShittingByUnitAsync(int unitId, Shitting shitting);
		Task DeleteAsync(Shitting shitting);
	}
}
