//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Doctrin.Core.Repositories;

namespace Doctrin.Data.Repositories
{
	public  class CrappingRepository : Repository<Crapping>, ICrappingRepository	{
		private readonly MyDbContext _context;


		public CrappingRepository(MyDbContext context) : base(context)
		{
			 _context = context;
		}
	}
}
