//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using System;
using System.Collections.Generic;

namespace Doctrin.Api.Resources
{
	public  class SaveCrappingResource 	{
		public String Value {get;set;} 


		public SaveCrappingResource() 
		{
			
		}
	}
}
