//Generated by Framework Code Generator5/7/2020 9:00:36 PM
using System;
using System.Collections.Generic;

namespace Doctrin.Api.Resources
{
	public  class ShittingResource 	{
		public Int32 Id {get;set;} 
		public String GlobalId {get;set;} 
		public String Value {get;set;} 
		public Int32 UnitId {get;set;} 


		public ShittingResource() 
		{
			
		}
	}
}
