//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;
using Doctrin.Core.Repositories;
using Doctrin.Core.Services;

namespace Doctrin.Services
{
	public  class CrappingService : ICrappingService	{
		private readonly IUnitOfWork _unitOfWork;


		public CrappingService(IUnitOfWork unitOfWork) 
		{
			this._unitOfWork = unitOfWork;
		}
		public async Task<Crapping> AddAsync(Crapping crappingToCreate)
		{
			await _unitOfWork.Crappings.AddAsync(crappingToCreate);
			await _unitOfWork.CommitAsync();
			return crappingToCreate;
		}
		
		public async Task DeleteAsync(Crapping crappingToDelete)
		{
			_unitOfWork.Crappings.Remove(crappingToDelete);
			await _unitOfWork.CommitAsync();
		}
		
		public async Task<Crapping> GetAsync(int id)
		{
			return await _unitOfWork.Crappings.GetByIdAsync(id);
		}
	}
}
