//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;

namespace Doctrin.Core.Repositories
{
	public  interface ICrappingRepository : IRepository<Crapping>	{

	}
}
