//Generated by Framework Code Generator5/5/2020 1:14:09 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;

namespace Doctrin.Core.Repositories
{
	public interface ISetting2Repository : IRepository<Shitting>	{


		Task<Shitting> GetSettingByUnitAsync(int unitId, int id);
		Task AddSettingByUnitAsync(int unitId, Shitting shitting);
	}
}
