//Generated by Framework Code Generator5/7/2020 9:00:36 PM
using Doctrin.Core.Entities;
using System.Threading.Tasks;

namespace Doctrin.Core.Repositories
{
	public  interface IShittingRepository : IRepository<Shitting>	{

		Task<Shitting> GetShittingByUnitAsync(int unitId, int id);
		Task AddShittingByUnitAsync(int unitId, Shitting shitting);
	}
}
