//Generated by Framework Code Generator5/8/2020 8:55:20 PM
using Doctrin.Core.Entities;
using Doctrin.Api.Resources;
using Doctrin.Api.Validators;
using Doctrin.Core.Services;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;

namespace Doctrin.Api.Controllers
{
	[Route("api/organisations/{unitId}/{entityName}")]
	public  class CrappingController : ControllerBase	{
		private readonly ICrappingService _crappingService;
		private readonly IMapper _mapper;


		public CrappingController(ICrappingService crappingService, IMapper mapper) 
		{
			_crappingService = crappingService;
			_mapper = mapper;
		}
		[HttpGet("{id}", Name= "GetCrapping")]
		public async Task<ActionResult<CrappingResource>> Get(int id)
		{
			if (id<1)
			{
				return BadRequest();
			}
			var crapping = await _crappingService.GetAsync(id);
			
			if (crapping==null)
			{
				return NotFound();
			}
			var crappingResource = _mapper.Map<Crapping,CrappingResource>(crapping);
			
			return Ok(crappingResource);
		}
		
		[HttpPost()]
		public async Task<ActionResult<CrappingResource>> Post([FromBody] SaveCrappingResource saveCrappingResource)
		{
			var validator = new SaveCrappingResourceValidator();
			var validationResult = await validator.ValidateAsync(saveCrappingResource);
			
			if (!validationResult.IsValid)
			return BadRequest(validationResult.Errors);
			
			var crappingToCreate = _mapper.Map<SaveCrappingResource, Crapping>(saveCrappingResource);
			
			var newCrapping = await _crappingService.AddAsync(crappingToCreate);
			
			var crapping = await _crappingService.GetAsync(newCrapping.Id);
			
			var crappingResource = _mapper.Map<Crapping, CrappingResource>(crapping);
			
			return CreatedAtRoute("GetCrapping",new {id =crapping.Id}, crappingResource);
		}
		
		
		[HttpDelete("{id}")]
		public async Task<IActionResult> Delete(int id)
		{
			if (id < 2) //don't allow deletion of root crapping
			return BadRequest();
			
			var crapping = await _crappingService.GetAsync(id);
			
			if (crapping == null)
			return NotFound();
			
			await _crappingService.DeleteAsync(crapping);
			
			return NoContent();
		}
	}
}
