//Generated by Framework Code Generator4/22/2020 9:41:07 PM
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Doctrin.Api.Controllers.Validators;
using Doctrin.Api.Resources;
using Doctrin.Core.Entities;
using Doctrin.Core.Services;
using Doctrin.Data;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace Doctrin.Web
{
	[Route("api/organisation")]
	public class SettingsController  : ControllerBase
    {

        private readonly ISettingService _settingService;
        private readonly IUnitService _unitService;

        private readonly IMapper _mapper;

        public SettingsController(ISettingService settingService,IUnitService unitService, IMapper mapper)
        {
            _settingService = settingService;
            _unitService = unitService;
            _mapper = mapper;
        }

        
        [HttpGet("{unitId}/settings/{globalId}", Name = "GetSetting")]
        public async Task<ActionResult<SettingResource>> Get(int unitId, string globalId)
        {
            if (unitId == 0 || globalId == "")
            {
                return BadRequest();
            }
            var setting = await _settingService.GetSettingByUnit(unitId, globalId);

            if (setting == null)
            {
                return NotFound();
            }
            var settingResource = _mapper.Map<Setting, SettingResource>(setting);

            return Ok(settingResource);
        }

        [HttpPost()]
        public async Task<ActionResult<SettingResource>> Post(int unitId, SaveSettingResource saveSettingResource)
        {
            var unit = await _unitService.GetAsync(unitId);
            if (unit == null)
            {
                return NotFound();
            }
            var validator = new SaveSettingResourceValidator();
            var validationResult = await validator.ValidateAsync(saveSettingResource);

            if (!validationResult.IsValid)
                return BadRequest(validationResult.Errors);

            var settingToCreate = _mapper.Map<SaveSettingResource, Setting>(saveSettingResource);

            var newSetting = await _settingService.Add(unitId, settingToCreate);

            var settingResource = _mapper.Map<Setting, SettingResource>(newSetting);

            return CreatedAtRoute("GetSetting", new { unitId = newSetting.UnitId, globalId =settingResource.GlobalId  }, settingResource);
        }


        [HttpDelete("{unitId}/settings/{globalId}")]
        public async Task<IActionResult> Delete(int unitId,string globalId)
        {
            if (unitId == 0 || globalId=="")
                return BadRequest();

            var setting = await _settingService.GetSettingByUnit(unitId, globalId);

            if (setting == null)
                return NotFound();

            await _settingService.Delete(setting);

            return NoContent();
        }

        [HttpPatch]
        public async Task<ActionResult<SettingResource>> Patch(int unitId,string globalId,JsonPatchDocument<SaveSettingResource> patchDocument)
        {
            var unit = await _unitService.GetAsync(unitId);
            if (unit==null)
            {
                return NotFound();
            }

            var settingToPatchFromRepository = await _settingService.GetSettingByUnit(unitId, globalId);
            if (settingToPatchFromRepository==null)
            {
                return NotFound();
            }

            var settingToPatchResource = _mapper.Map<SaveSettingResource>(settingToPatchFromRepository);

            patchDocument.ApplyTo(settingToPatchResource);

            var settingToPatchFrom = _mapper.Map<Setting>(settingToPatchResource);

            //await _mapper.Map(settingToPatchResource,settingToPatchFromRepository);

            await _settingService.Update(settingToPatchFromRepository, settingToPatchFrom);



            return Ok(settingToPatchResource);
        }

    }
}
