//Generated by Framework Code Generator5/7/2020 9:00:36 PM
using Doctrin.Core.Entities;
using Doctrin.Api.Resources;
using Doctrin.Api.Validators;
using Doctrin.Core.Services;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;

namespace Doctrin.Api.Controllers
{
	[Route("api/organisations/{unitId}/{entityName}")]
	public  class ShittingController : ControllerBase	{
		private readonly IUnitService _unitService;
		private readonly IShittingService _shittingService;
		private readonly IMapper _mapper;


		public ShittingController(IUnitService unitService,IShittingService shittingService, IMapper mapper) 
		{
			_unitService = unitService;
			_shittingService = shittingService;
			_mapper = mapper;
		}
		[HttpGet('{id}', Name = 'GetShitting')]
		public async Task<ActionResult<ShittingResource>> Get(int unitId, int id)
		{
			if (unitId < 1 || id<1)
			{
				return BadRequest();
			}
			
			var shitting = await _shittingService.GetShittingByUnitAsync(unitId, id);
			
			if (shitting == null)
			{
				return NotFound();
			}
			var shittingResource = _mapper.Map<Shitting, ShittingResource>(shitting);
			
			return Ok(shittingResource);
		}
		
		[HttpPost()]
		public async Task<ActionResult<ShittingResource>> Post(int unitId, SaveShittingResource saveShittingResource)
		{
			if (unitId < 1 )
			{
				return BadRequest();
			}
			
			var unit = await _unitService.GetAsync(unitId);
			if (unit == null)
			{
				return NotFound();
			}
			var validator = new SaveShittingResourceValidator();
			var validationResult = await validator.ValidateAsync(saveShittingResource);
			
			if (!validationResult.IsValid)
			return BadRequest(validationResult.Errors);
			
			var shittingToCreate = _mapper.Map<SaveShittingResource, Shitting>(saveShittingResource);
			
			var newShitting = await _shittingService.AddAsync(unitId, shittingToCreate);
			
			var shittingResource = _mapper.Map<Shitting, ShittingResource>(newShitting);
			
			return CreatedAtRoute('GetShitting', new { unitId = newShitting.UnitId, id = shittingResource.GlobalId }, shittingResource);
		}
		
		
		[HttpDelete('{id}')]
		public async Task<IActionResult> Delete(int unitId, int id)
		{
			if (unitId < 1 || id<1)
			{
				return BadRequest();
			}
			
			var shitting = await _shittingService.GetShittingByUnitAsync(unitId, id);
			
			if (shitting == null)
			return NotFound();
			
			await _shittingService.DeleteAsync(shitting);
			
			return NoContent();
		}
		
		[HttpPatch]
		public async Task<ActionResult<ShittingResource>> Patch(int unitId, int id, [FromBody] JsonPatchDocument<SaveShittingResource> patchDocument)
		{
			if (unitId <1 || id<1 || patchDocument==null)
			{
				return BadRequest();
			}
			
			var unit = await _unitService.GetAsync(unitId);
			if (unit == null)
			{
				return NotFound();
			}
			
			var shittingToPatchFromRepository = await _shittingService.GetShittingByUnitAsync(unitId, id);
			if (shittingToPatchFromRepository == null)
			{
				return NotFound();
			}
			
			var shittingToPatchResource = _mapper.Map<SaveShittingResource>(shittingToPatchFromRepository);
			
			patchDocument.ApplyTo(shittingToPatchResource);
			
			var shittingToPatchFrom = _mapper.Map<Shitting>(shittingToPatchResource);
			
			await _shittingService.UpdateAsync(shittingToPatchFromRepository, shittingToPatchFrom);
			
			return Ok(shittingToPatchResource);
		}
	}
}
